apiVersion: v1
kind: Service
metadata:
  name: openldap
  namespace: ldap
spec:
  ports:
  - name: openldap-first
    port: 636
    targetPort: 636
  - name: openldap-second
    port: 389
    targetPort: 389 
  selector:
    app: openldap
